### ISSUE TITLE
Fabric Capes Support

### ISSUE THREAD

**Issue by Lukebb04** [Camotoy/BedrockSkinUtility#3]
[https://www.curseforge.com/minecraft/mc-mods/capes](https://www.curseforge.com/minecraft/mc-mods/capes)

`@Redirect conflict. Skipping BedrockSkinUtility.mixins.json:CapeFeatureRendererMixin->@Redirect::solidToTranslucent(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000, already redirected by capes.mixins.json:MixinCapeFeatureRenderer->@Redirect::fixCapeTransparency(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000`

**Comment by Camotoy** [comment]
This doesn't prevent either mod from loading, correct?

**Comment by HandyHat** [comment]
If both Fabric Capes and BedrockSkinUtility are installed the game does not get to the main menu and instead keeps reloading the resource pack (the red Mojang screen with the loading bar shows up)

Log:
```
[Render thread/WARN]: @Redirect conflict. Skipping BedrockSkinUtility.mixins.json:CapeFeatureRendererMixin->@Redirect::solidToTranslucent(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000, already redirected by capes.mixins.json:MixinCapeFeatureRenderer->@Redirect::fixCapeTransparency(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; with priority 1000
[Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:780) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179) ~[intermediary-1.17.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) [intermediary-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_5619.method_32198(class_5619.java:24) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.redirect$zcn000$createPlayerEntityRenderer(class_5619.java:573) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.method_32175(class_5619.java:164) ~[intermediary-1.17.1.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[guava-21.0.jar:?]
	at net.minecraft.class_5619.method_32177(class_5619.java:162) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:370) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 104 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector solidToTranslucent(Lnet/minecraft/class_2960;)Lnet/minecraft/class_1921; in BedrockSkinUtility.mixins.json:CapeFeatureRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap BedrockSkinUtility-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_5619.method_32198(class_5619.java:24) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.redirect$zcn000$createPlayerEntityRenderer(class_5619.java:573) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.method_32175(class_5619.java:164) ~[intermediary-1.17.1.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:146) ~[guava-21.0.jar:?]
	at net.minecraft.class_5619.method_32177(class_5619.java:162) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:370) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 104 more

**Comment by Camotoy** [comment]
Labelling as a confirmed bug as it is plausible given the knowledge I have between both codebases. I'll try to fix this next week.
